language: elixir

env:
  global:
    - MIX_ENV=test
  matrix:
    - VER_INFLUXDB=0.9.6
    - VER_INFLUXDB=0.10.0

matrix:
  allow_failures:
    - env: VER_INFLUXDB=0.10.0

before_install:
  - mkdir "${HOME}/go"
  - export GOPATH="${HOME}/go"
  - export PATH="${GOPATH}/bin:${PATH}"
  - mkdir -p "${GOPATH}/src/github.com/influxdb"
  - cd "${GOPATH}/src/github.com/influxdb"
  - wget "https://github.com/influxdb/influxdb/archive/v${VER_INFLUXDB}.tar.gz" -O influxdb.tar.gz && tar -xf influxdb.tar.gz
  - mv "influxdb-${VER_INFLUXDB}" influxdb
  - cd "${GOPATH}/src/github.com/influxdb/influxdb"
  - git init .
  - go get ./...
  - go build ./...
  - go install ./...
  - cd "${TRAVIS_BUILD_DIR}"

before_script:
  - influxd config > ./influxdb.conf
  - nohup "${GOPATH}/bin/influxd" -pidfile ./influxdb.pid -config ./influxdb.conf >>./influxdb.stdout 2>>./influxdb.stderr &
  - sleep 5

  - curl "http://localhost:8086/query?q=CREATE%20USER%20instream_test%20WITH%20PASSWORD%20%27instream_test%27%20WITH%20ALL%20PRIVILEGES"
  - curl "http://localhost:8086/query?q=CREATE%20USER%20instream_guest%20WITH%20PASSWORD%20%27instream_guest%27"
  - sed -i 's/auth-enabled = false/auth-enabled = true/' ./influxdb.conf
  - echo -e "[[udp]]\n  enabled = true\n  bind-address = \":8089\"\n  database = \"test_database\"\n  batch-size = 1000\n  batch-timeout = \"1s\"\n  batch-pending = 5\n" >> ./influxdb.conf


  - kill `cat ./influxdb.pid`
  - nohup "${GOPATH}/bin/influxd" -pidfile ./influxdb.pid -config ./influxdb.conf >>./influxdb.stdout 2>>./influxdb.stderr &
  - sleep 5

after_failure:
  - echo "==> config <=="
  - cat ./influxdb.conf
  - echo "==> stdout <=="
  - cat ./influxdb.stdout
  - echo "==> stderr <=="
  - cat ./influxdb.stderr

after_success:
  - mix coveralls.travis

after_script:
  - kill `cat ./influxdb.pid`
