language:    elixir
otp_release: 18.0
elixir:      1.2.6

env:
  global:
    - MIX_ENV=test
  matrix:
    - VER_GO=1.6.2 VER_INFLUXDB=v1.0.2
    - VER_GO=1.7.3 VER_INFLUXDB=v1.1.5
    - VER_GO=1.7.4 VER_INFLUXDB=v1.2.3 TRAVIS_COVERAGE=true
    - VER_GO=1.7.4 VER_INFLUXDB=master

matrix:
  include:
    - elixir: 1.3.4
      env:    VER_GO=1.7.4 VER_INFLUXDB=v1.2.3
    - elixir: 1.4.2
      env:    VER_GO=1.7.4 VER_INFLUXDB=v1.2.3
    - elixir:      1.4.2
      env:         VER_GO=1.7.4 VER_INFLUXDB=v1.2.3
      otp_release: 19.0
  allow_failures:
    - env: VER_GO=1.7.4 VER_INFLUXDB=master

before_install:
  - eval "$(gimme ${VER_GO})"

  - mkdir "${HOME}/go"
  - export GOPATH="${HOME}/go"
  - export PATH="${GOPATH}/bin:${PATH}"

  - go get github.com/sparrc/gdm

  - mkdir -p "${GOPATH}/src/github.com/influxdata"
  - cd "${GOPATH}/src/github.com/influxdata"
  - wget "https://github.com/influxdata/influxdb/archive/${VER_INFLUXDB}.tar.gz" -O influxdb.tar.gz && tar -xf influxdb.tar.gz
  - find . -maxdepth 1 -type d -name 'influxdb*' -exec mv {} influxdb \;
  - cd "${GOPATH}/src/github.com/influxdata/influxdb"
  - git init .
  - gdm restore
  - go clean ./...
  - sed -i -e "s/version = \"unknown\"/version = \"${VER_INFLUXDB//v}\"/g" cmd/influxd/main.go
  - go install ./...
  - cd "${TRAVIS_BUILD_DIR}"

before_script:
  - influxd config > ./influxdb.conf
  - nohup "${GOPATH}/bin/influxd" -pidfile ./influxdb.pid -config ./influxdb.conf >>./influxdb.stdout 2>>./influxdb.stderr &
  - sleep 5

  - curl -XPOST 'http://localhost:8086/query' --data-urlencode "q=CREATE USER instream_test WITH PASSWORD 'instream_test' WITH ALL PRIVILEGES"
  - curl -XPOST 'http://localhost:8086/query' --data-urlencode "q=CREATE USER instream_guest WITH PASSWORD 'instream_guest'"
  - sed -i 's/auth-enabled = false/auth-enabled = true/' ./influxdb.conf
  - echo -e "[[udp]]\n  enabled = true\n  bind-address = \":8089\"\n  database = \"test_database\"\n  batch-size = 1000\n  batch-timeout = \"1s\"\n  batch-pending = 5\n" >> ./influxdb.conf

  - kill `cat ./influxdb.pid`
  - nohup "${GOPATH}/bin/influxd" -pidfile ./influxdb.pid -config ./influxdb.conf >>./influxdb.stdout 2>>./influxdb.stderr &
  - sleep 5

after_failure:
  - echo "==> config <=="
  - cat ./influxdb.conf
  - echo "==> stdout <=="
  - cat ./influxdb.stdout
  - echo "==> stderr <=="
  - cat ./influxdb.stderr

after_success: |
  if [ ! -z "${TRAVIS_COVERAGE}" ]; then
    mix coveralls.travis
  fi

after_script:
  - kill `cat ./influxdb.pid`
